on:
  release:
    types:
      - created

env:
  FILE_NAME: sl
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: tag

      - uses: actions/checkout@v3
        with:
          path: main
          ref: main

      - id: build_files
        run: |
          mkdir release
          cd tag/src
          tar --owner=0 --group=0 -cJf ../../release/${{ env.FILE_NAME }}-${{ github.event.release.name}}-noarch-1.txz *
          cd ../../release
          sha256sum ${{ env.FILE_NAME }}-${{ github.event.release.name}}-noarch-1.txz | awk '{print $1}' > ${{ env.FILE_NAME }}-${{ github.event.release.name}}-noarch-1.txz.sha256
          echo "checksum=$(cat ${{ env.FILE_NAME }}-${{ github.event.release.name}}-noarch-1.txz.sha256)" >> $GITHUB_OUTPUT

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/*

      - name: Add checksum to release description
        uses: djn24/add-comment-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          comment: |-
            ${{ env.FILE_NAME }}-${{ github.event.release.name}}-noarch-1.txz : ${{ steps.build_files.outputs.checksum }}
